# Movie Recommendation System

In [1]:
import pandas as pd
import numpy as np
# Converts string into list
import ast

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [7]:
# THE COLUMNS THAT NEEDS TO BE KEPT
# genres
# id
# keywords
# overview
# title
# cast
# crew
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [8]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [9]:
# Counting all the null values in each column
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
# Dropping all the null values as the the null value is negligible
movies.dropna(inplace=True)

In [11]:
# To check the duplicate values if present or not
movies.duplicated().sum()

0

In [12]:
# This is present in a wierd format (dictionary inside a dictionary)
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj) :
        L.append(i['name'])
    return L

In [14]:
movies.genres = movies.genres.apply(convert)

In [15]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [16]:
movies.keywords = movies.keywords.apply(convert)

In [17]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [18]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj) :
        if counter !=3:
            L.append(i['name'])
            counter++1
        else:
            break
    return L

In [19]:
movies.cast = movies.cast.apply(convert3)

In [20]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [21]:
def fetch_director(obj):
    L = []
    for j in ast.literal_eval(obj):
        if (j['job'] == 'Director'):
            L.append(j['name'])
            break
    return L

In [22]:
movies.crew = movies.crew.apply(fetch_director)

In [23]:
movies.overview = movies.overview.apply(lambda x:x.split())

In [24]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]

In [25]:
movies.genres = movies.genres.apply(lambda x:[i.replace(" ","") for i in x])
movies.keywords = movies.keywords.apply(lambda x:[i.replace(" ","") for i in x])
movies.crew = movies.crew.apply(lambda x:[i.replace(" ","") for i in x])
movies.cast = movies.cast.apply(lambda x:[i.replace(" ","") for i in x])

In [26]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]

In [27]:
movies['tags'] = movies.overview + movies.genres + movies.keywords + movies.cast + movies.crew

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [29]:
new_df = movies[['movie_id', 'title', 'tags']]
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [30]:
# Converting a list into string 
new_df.tags = new_df.tags.apply(lambda x: " ".join(x))

/usr/local/lib/python3.9/site-packages/pandas/core/generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [31]:
new_df.tags[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [32]:
new_df.tags = new_df.tags.apply(lambda x:x.lower())

In [33]:
new_df.head(2)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [35]:
vectors = cv.fit_transform(new_df.tags).toarray()

In [36]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980s',
 '19th',
 '19thcentury',
 '20',
 '20th',
 '24',
 '25',
 '30',
 '3d',
 '40',
 '50',
 '60',
 '60s',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'aasifmandvi',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'ability',
 'able',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepts',
 'access',
 'accident',
 'accidentally',
 'accompanied',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'action',
 'actions',
 'activist',
 'activities',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adambrody',
 'adamgoldberg',
 'adamlefevre',
 'adams',
 'adamsandler',
 'adamscott',
 'adamshankman',
 'adaptation',
 'addict',
 'addicted',
 'addiction',
 'adewaleakinnuoye',
 'adolescence',
 'adopted',
 'adoption',
 'adrianmartinez',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'agbaje',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airport',
 'al',
 'alanalda',
 'alanarkin',
 'alancumming',
 'alanrickman',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrooks',
 'albertfinney',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alessandronivola',
 'alex',
 'alexandersiddig',
 'alexapenavega',
 'alexborstein',
 'alexisbledel',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alice',
 'alicedrummond',
 'aliciawitt',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alilarter',
 'alive',
 'allancorduner',
 'allen',
 'allencovert',
 'alleong',
 'alliance',
 'allied',
 'allies',
 'allisonjanney',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amazing',
 'ambassador',
 'amberheard',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amy',
 'amyadams',
 'amypoehler',
 'amyryan',
 'amysedaris',
 'amysmart',
 'anagasteyer',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andreamartin',
 'andrebraugher',
 'andrew',
 'andrewdaly',
 'android',
 'andy',
 'andydick',
 'andygarcía',
 'andyrichter',
 'andysamberg',
 'andyserkis',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angelo',
 'anger',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annafaris',
 'annakendrick',
 'annalevine',
 'annapaquin',
 'annasophiarobb',
 'anndowd',
 'anne',
 'annebancroft',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annemoss',
 'annettebening',
 'annie',
 'annikapergament',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antonicorone',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'appear',
 'appears',
 'apple',
 'apprentice',
 'approaches',
 'april',
 'arab',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'arena',
 'arielwinter',
 'arise',
 'aristocrat',
 'armed',
 'arminmueller',
 'arms',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'art',
 'arthur',
 'arthurj',
 'arthurtovey',
 'artificialintelligence',
 'artist',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'ask',
 'asked',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'asteroid',
 'astronaut',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attention',
 'attitude',
 'attorney',
 'attraction',
 'attractive',
 'audience',
 'audition',
 'august',
 'aunjanueellis',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'auto',
 'avaacres',
 'avenge',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'azizansari',
 'baby',
 'bachelor',
 'backdrop',
 'bad',
 'bahamas',
 'bail',
 'bailey',
 'bailing',
 'baker',
 'balance',
 'ball',
 'ballet',
 'band',
 'banished',
 'bank',
 'banker',
 'bankrobbery',
 'baptiste',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrypepper',
 'barryshabakahenley',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beat',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'beccasweitzer',
 'becominganadult',
 'bed',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'beloved',
 'ben',
 'benaffleck',
 'benchaplin',
 'benedictcumberbatch',
 'benfoster',
 'bengazzara',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstiller',
 'bent',
 'benwhishaw',
 'berlin',
 'bernardhill',
 'bernardlee',
 'berniemac',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'bethgrant',
 'betrayal',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'biggest',
 'biker',
 'billcamp',
 'billcobbs',
 'billduke',
 'billhader',
 'billionaire',
 'billmoseley',
 'billmurray',
 'billnighy',
 'billnunn',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyburke',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'billydeewilliams',
 'billyslaughter',
 'billyzane',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmail',
 'blackpeople',
 'blade',
 'blake',
 'blakeclark',
 'blind',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'blythedanner',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobbalaban',
 'bobbergen',
 'bobby',
 'bobbycannavale',
 'bobbyfarrelly',
 'bobgunton',
 'bobhoskins',
 'bobstephenson',
 'body',
 'bodyguard',
 'bokeemwoodbine',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonniehunt',
 'book',
 'books',
 'border',
 'bored',
 'boring',
 'born',
 'boss',
 'boston',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boydbanks',
 'boydholbrook',
 'boyfriend',
 'boys',
 'braddourif',
 'bradgarrett',
 'bradleycooper',
 'bradleywhitford',
 'bradpitt',
 'bradwilliamhenke',
 'brain',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breaking',
 'breaks',
 'breckinmeyer',
 'brendanfraser',
 'brendangleeson',
 'brendansextoniii',
 'brentbriscoe',
 'brentspiner',
 'brettcullen',
 'brettratner',
 'brian',
 'briancox',
 'briandennehy',
 'briandepalma',
 'briandoyle',
 'brianj',
 'bride',
 'bridge',
 'bridgettewilson',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbell',
 'brucedern',
 'brucegreenwood',
 'brucemcgill',
 'brucespence',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryan',
 'bryancranston',
 'bryansinger',
 'brycedallashoward',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'buried',
 'burns',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'busy',
 'butler',
 'buy',
 'byrne',
 'cabin',
 'california',
 'called',
 'calls',
 'callumkeithrennie',
 'calvin',
 'came',
 'camera',
 'cameras',
 'cameron',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'cannibal',
 'capable',
 'capitalism',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'caraseymour',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagallo',
 'carlagugino',
 'carlosalazraqui',
 'carmen',
 'carmenelectra',
 'carolineaaron',
 'carolinegoodall',
 'carolkane',
 'carpenter',
 'carrace',
 'carrie',
 'carriefisher',
 'carry',
 'carrying',
 'cars',
 'carter',
 'cary',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherineo',
 'catherinezeta',
 'cathey',
 'catholic',
 'catholicism',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'cedrictheentertainer',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'celiaimrie',
 'celiaweston',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'certain',
 'chadmichaelmurray',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'chancekelly',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlesdance',
 'charlesdurning',
 'charlesnapier',
 'charless',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotterampling',
 'charltonheston',
 'charm',
 'charming',
 'chase',
 'chased',
 'chazzpalminteri',
 'cheating',
 'cheechmarin',
 'cheerleader',
 'chef',
 'chelcieross',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhood',
 'children',
 'chilling',
 'chimcbride',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisellis',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrismessina',
 'chrismiller',
 'chriso',
 'chrisparnell',
 'chrispenn',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christinebaranski',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherguest',
 'christopherlambert',
 'christopherlee',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'church',
 'cia',
 'ciaránhinds',
 'cillianmurphy',
 'circle',
 'circumstances',
 'circus',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkgregg',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'claudevandamme',
 'cleaduvall',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurtis',
 'cliftoncollinsjr',
 'climbing',
 'clinteastwood',
 'clinthoward',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'cohen',
 'cold',
 'coldwar',
 'cole',
 'colehauser',
 'colinfarrell',
 'colinfirth',
 'colinhanks',
 'colinsalmon',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'colleencamp',
 'college',
 'collide',
 'collins',
 'collision',
 'colmfeore',
 'colmmeaney',
 'colonel',
 'colony',
 'colorful',
 'coma',
 'combat',
 'come',
 'comeback',
 'comedian',
 'comedy',
 'comes',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'compton',
 'computer',
 'concert',
 'condition',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connienielsen',
 'connieray',
 'connor',
 'conquer',
 'conradvernon',
 'conscience',
 'consequences',
 'conspiracy',
 'constantly',
 'construction',
 'contact',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controversial',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'coreyburton',
 'coreystoll',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 ...]

In [38]:
# Now we are going to apply stemming which removes the similar words
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [39]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [40]:
new_df.tags = new_df.tags.apply(stem)

/usr/local/lib/python3.9/site-packages/pandas/core/generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [41]:
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df.tags).toarray()
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930',
 '1940',
 '1950',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '20th',
 '24',
 '25',
 '30',
 '3d',
 '40',
 '50',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'aasifmandvi',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'abov',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adambrodi',
 'adamgoldberg',
 'adamlefevr',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adewaleakinnuoye',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrianmartinez',
 'adrienbrodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'agbaj',
 'age',
 'agediffer',
 'agency',
 'agenda',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airport',
 'al',
 'alanalda',
 'alanarkin',
 'alancum',
 'alanrickman',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcohol',
 'alecbaldwin',
 'alessandronivola',
 'alex',
 'alexandersiddig',
 'alexapenavega',
 'alexborstein',
 'alexisbledel',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alic',
 'alice',
 'alicedrummond',
 'aliciasilverston',
 'aliciawitt',
 'alien',
 'alieninvas',
 'alienlife',
 'alilart',
 'aliv',
 'alive',
 'allancordun',
 'allen',
 'allencovert',
 'alleong',
 'alli',
 'allianc',
 'allisonjanney',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanfootbal',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amus',
 'amusementpark',
 'amyadam',
 'amypoehl',
 'amyryan',
 'amysedari',
 'amysmart',
 'anagastey',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'anderson',
 'andi',
 'andiemacdowel',
 'andreamartin',
 'andrebraugh',
 'andrew',
 'andrewdali',
 'android',
 'andydick',
 'andygarcía',
 'andyricht',
 'andysamberg',
 'andyserki',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'angelo',
 'anger',
 'angle',
 'angri',
 'angusmacinn',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'annalevin',
 'annapaquin',
 'annasophiarobb',
 'anndowd',
 'anne',
 'annebancroft',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annikaperga',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antihero',
 'antonicoron',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'archaeologist',
 'architect',
 'arci',
 'arctic',
 'area',
 'arena',
 'argument',
 'arielwint',
 'arigraynor',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'arminmueller',
 'armor',
 'armsdeal',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'arthurj',
 'arthurtovey',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atomicbomb',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunjanueelli',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'avaacr',
 'aveng',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'azizansari',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'balanc',
 'ball',
 'ballet',
 'band',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bankrobberi',
 'baptist',
 'bar',
 'barbarahershey',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrypepp',
 'barryshabakahenley',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'bdwong',
 'beach',
 'bear',
 'beast',
 'beat',
 'beaubridg',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'beccasweitz',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'benchaplin',
 'bend',
 'benedictcumberbatch',
 'benedictwong',
 'benfost',
 'bengazzara',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstil',
 'bent',
 'benwhishaw',
 'berlin',
 'bernardhil',
 'bernardle',
 'berniemac',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'bethgrant',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'beverlyd',
 'bibl',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billcamp',
 'billcobb',
 'billduk',
 'billhad',
 'billi',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billnunn',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyburk',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'billydeewilliam',
 'billyslaught',
 'billywest',
 'billyzan',
 'biographi',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blakeclark',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'blythedann',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbalaban',
 'bobbergen',
 'bobbi',
 'bobbycannaval',
 'bobbyfarrelli',
 'bobbymoynihan',
 'bobclendenin',
 'bobgunton',
 'bobhoskin',
 'bobodenkirk',
 'bobstephenson',
 'bodi',
 'body',
 'bodyguard',
 'bokeemwoodbin',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boydbank',
 'boydholbrook',
 'boyfriend',
 'boys',
 'braddourif',
 'bradgarrett',
 'bradleycoop',
 'bradleywhitford',
 'bradpitt',
 'bradwilliamhenk',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breckinmey',
 'brendanfras',
 'brendangleeson',
 'brendansextoniii',
 'brentbrisco',
 'brentspin',
 'brettcullen',
 'brettratn',
 'brian',
 'briancox',
 'briandennehi',
 'briandepalma',
 'briandoyle',
 'brianj',
 'briano',
 'bride',
 'bridg',
 'bridgettewilson',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadway',
 'broke',
 'broken',
 'brook',
 'brooklyn',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucemcgil',
 'brucesp',
 'brucewilli',
 'brutal',
 'bryan',
 'bryancranston',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddycomedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'burglar',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butler',
 'buy',
 'byrn',
 'cabin',
 'cal',
 'california',
 'callumkeithrenni',
 'calvin',
 'came',
 'camera',
 'cameron',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbel',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'cannib',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'caraseymour',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagallo',
 'carlagugino',
 'carlo',
 'carlosalazraqui',
 'carmen',
 'carmenelectra',
 'carol',
 'carolineaaron',
 'carolinegoodal',
 'carolkan',
 'carrac',
 'carri',
 'carrie',
 'carriefish',
 'carter',
 'cary',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathey',
 'cathol',
 'catholic',
 'caught',
 'caus',
 'cave',
 'cedrictheentertain',
 'celebr',
 'celiaimri',
 'celiaweston',
 'cellphon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'century',
 'certain',
 'chadmichaelmurray',
 'chain',
 'chainsaw',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chancekelli',
 'chang',
 'channingtatum',
 'chao',
 'chaos',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charlesd',
 'charlesdurn',
 'charlesnapi',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotterampl',
 'charltonheston',
 'charm',
 'chase',
 'chazzpalminteri',
 'cheat',
 'cheechmarin',
 'cheerlead',
 'chef',
 'chelcieross',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhood',
 'children',
 'chill',
 'chimcbrid',
 'china',
 'chines',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigni',
 'choic',
 'choos',
 'chosen',
 'chri',
 'chrisbrown',
 'chriscolumbu',
 'chriscoop',
 'chriselli',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrismessina',
 'chrismil',
 'chriso',
 'chrisparnel',
 'chrispenn',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christinaappleg',
 'christinaricci',
 'christinebaranski',
 'christma',
 'christmas',
 'christmasparti',
 'christoph',
 'christopherguest',
 'christopherlambert',
 'christopherle',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chronicl',
 'church',
 'cia',
 'ciaránhind',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkgregg',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'cleaduval',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurti',
 'cliftoncollinsjr',
 'climat',
 'climb',
 'clinteastwood',
 'clinthoward',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'coach',
 'coast',
 'cocain',
 'code',
 'codycameron',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colinfarrel',
 'colinfirth',
 'colinhank',
 'colinsalmon',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleencamp',
 'colleg',
 'college',
 'collid',
 'collin',
 'collis',
 'colmfeor',
 'colmmeaney',
 'colonel',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compton',
 'comput',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connel',
 'connienielsen',
 'connieray',
 'connor',
 'conquer',
 'conradvernon',
 'consequ',
 'consequences',
 'consid',
 'conspir',
 'conspiraci',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'core',
 'coreyburton',
 'coreystol',
 'corner',
 'corpor',
 'corps',
 'corrupt',
 'cost',
 'costum',
 'couldn',
 'count',
 'countri',
 'country',
 ...]

In [42]:
# Here we are going to use Cosine distance
# Cosine distance calculates the anlgle between 2 lines
# Here we don't use Euclidean distance as we are dealing with data in a higher dimension
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
similarity = cosine_similarity(vectors)

In [44]:
# Fetching the index of each movies
new_df[new_df['title'] == 'Batman Begins'].index[0]

119

In [45]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key = lambda x:x[1])[1:6]
    
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [47]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman
Rockaway